### ISSUE TITLE
Error: fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by philthynz** [sondree/b2_fuse#10]
I have an error when trying to mount:

```
# python b2fuse.py /mnt/backblaze
2016-07-22 22:22:07,903:INFO:list_buckets
fuse: device not found, try 'modprobe fuse' first
Traceback (most recent call last):
  File "b2fuse.py", line 499, in <module>
    main(args.mountpoint, args.account_id, args.application_key, args.bucket_id)
  File "b2fuse.py", line 492, in main
    FUSE(filesystem, mountpoint, nothreads=True, foreground=True)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 480, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

config.yaml:

```
# cat config.yaml 
accountId: "id"
applicationKey: "key"
bucketId: "id"
```

Also, now that BB support files with any size. is b2 fuse only limited to the ram? If so have you had any experience in using a ram drive for this. What i would like to use BB for is to extend the VPS storage for a NAS.

**Comment by falense** [comment]
I have never seen this error before. Have you installed fusepy as described in readme?

For the current stable version the entire file has to fit in memory. In an upcoming version I intend to add the possibility of storing files temporarily on disk (v1.3).

I have not experimented with a ram drive for this. By ram drive do you mean virtual disk backed by ram? If yes, this would not help you at all since b2fuse currently uses ram storage directly. You could in theory increase your swap size in order to fit larger files, but I have not done any tests with this kind of setup. It may slow down the host significantly as the swapping affects other processes.

**Comment by falense** [comment]
Closing for inactivity.
