### ISSUE TITLE
Trouble finding fuse / invalid token

### ISSUE THREAD

**Issue by yatahaze** [sondree/b2_fuse#13]
I have fuse and libfuse installed via package repo, and I'm getting the following error:

```
# python b2fuse.py /srv/b2
Traceback (most recent call last):
  File "b2fuse.py", line 35, in <module>
    from fuse import FUSE, FuseOSError, Operations
ImportError: No module named fuse
```

I know im not supposed to use python-fuse I think, but installing it results in a slightly different error:

```
# python b2fuse.py /srv/b2
Traceback (most recent call last):
  File "b2fuse.py", line 35, in <module>
    from fuse import FUSE, FuseOSError, Operations
ImportError: cannot import name FUSE
```

The python3 command gives me this error:

```
# python3 b2fuse.py /srv/b2
  File "b2fuse.py", line 172
    return dict(st_mode=(S_IFDIR | 0777), st_ctime=time(), st_mtime=time(), st_atime=time(), st_nlink=2)
                                      ^
SyntaxError: invalid token
```

I'm pretty sure I'm just an idiot... any ideas? Using openSuSE 13.1.

**Comment by ppolewicz** [comment]
`python --version`?
