### ISSUE TITLE
Getting URLError

### ISSUE THREAD

**Issue by nic96** [sondree/b2_fuse#19]
My log keeps getting filled with URLErrors when using b2local.py. It downloads files fine, but it doesn't seem to upload any files.

```
Exception in thread Thread-810:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/b2_fuse/b2local.py", line 211, in _download_thread
    self.download_file(b2_filename, local_filename)
  File "/opt/b2_fuse/b2local.py", line 185, in download_file
    data = self.bucket.get_file(b2_filename)
  File "/opt/b2_fuse/b2bucket_threaded.py", line 134, in get_file
    return super(B2BucketThreaded,self).get_file(filename)
  File "/opt/b2_fuse/b2bucket.py", line 214, in get_file
    return self._get_file(*args)
  File "/opt/b2_fuse/b2bucket.py", line 181, in _get_file
    with OpenUrl(api_url, None, encoded_headers) as resp:
  File "/opt/b2_fuse/b2_python_pusher.py", line 61, in __enter__
    self.file = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by falense** [comment]
Apologies for the late response. 

B2Fuse local was an experiment in attempting to replicate Dropbox like behaviour. This is difficult to achieve consistently and is being discontinued with version 1.3. If you want to have a local copy I suggest using unison to sync a local folder to the online folder. 

Best
Sondre
