### ISSUE TITLE
How to run b2_fuse in a Docker container?

### ISSUE THREAD

**Issue by pascalandy** [sondree/b2_fuse#36]
I'm using AWS S3 at this point and I would like to use another Datacenter as well. As I'm a Docker fan, I'm wondering if anyone created a container out of this project?

If this can inspire anyone else, here is my Dockerfile for AWS CLI (S3):

```
FROM phusion/baseimage:0.9.19

# Install these apps
RUN \
    apt-get update && apt-get install -y \
    nano \
    rsync \
    unzip \
    gzip \
    wget \
    openssl \
    ntp \
    secure-delete \
    git \
    git-core \
    python2.7 \
    curl \
    groff && \
    curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    pip install awscli && \
    aws help && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    echo "apt-get install is finished" && \
    echo

WORKDIR /root

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]
```

**Comment by falense** [comment]
I am not sure I understand what you wish for. A docker image that has B2Fuse installed?

**Comment by pascalandy** [comment]
Yes exactly! Trying to avoid AWS locked in.

**Comment by falense** [comment]
I don't have docker installed and my distro does not have a working docker package, but you could try this: 

```FROM phusion/baseimage:0.9.19

# Install these apps
RUN \
    apt-get update && apt-get install -y \
    nano \
    rsync \
    unzip \
    gzip \
    wget \
    openssl \
    ntp \
    secure-delete \
    git \
    git-core \
    python2.7 \
    curl \
    groff && \
    curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    pip install awscli && \
    pip install b2 && \
    git clone https://github.com/sondree/b2_fuse && \
    aws help && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    echo "apt-get install is finished" && \
    echo

WORKDIR /root

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]
```

**Comment by pascalandy** [comment]
Thanks I'll try it :)

**Comment by pascalandy** [comment]
Ok here is my Dockerfile.

I removed `python3 get-pip.py` as it could not be found.

```
# project: python-fire_b2_fuse
# https://github.com/sondree/b2_fuse
FROM python:3.5.2

RUN \
	apt-get update -q && apt-get -qy upgrade && \
	curl -O https://bootstrap.pypa.io/get-pip.py && \
	apt-get install -qy --no-install-recommends \
		\
		nano \
		wget \
		git \
		\
		python-yaml \
		python-pip && \
		\
		pip install fusepy && \
		pip install b2 && \
		\
		git clone https://github.com/sondree/b2_fuse && \
		\
		echo "Let's clean up the shop" && \
		apt-get clean && \
		rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    	echo "apt-get install is finished"
	
WORKDIR /b2_fuse
```

Everything is builds normally. I docker exec into the container. (Here is how the FROM image [was build](https://github.com/docker-library/python/blob/693a75332e8ae5ad3bfae6e8399c4d7cc3cb6181/3.5/Dockerfile))

I cd here:

```
root@0cc7691cbb6f:/b2_fuse# pwd
/b2_fuse
root@0cc7691cbb6f:/b2_fuse# ls -lh
total 72K
-rw-r--r-- 1 root root 1.1K Dec 12 20:09 LICENSE
-rwxr-xr-x 1 root root 5.4K Dec 12 20:09 README.md
-rw-r--r-- 1 root root 3.7K Dec 12 20:09 b2fuse.py
-rw-r--r-- 1 root root  15K Dec 12 20:09 b2fuse_main.py
-rw-r--r-- 1 root root 3.1K Dec 12 20:09 cached_bucket.py
-rw-r--r-- 1 root root  119 Dec 12 20:14 config.yaml
-rw-r--r-- 1 root root 4.6K Dec 12 20:09 directory_structure.py
drwxr-xr-x 2 root root 4.0K Dec 12 20:09 filetypes
-rwxr-xr-x 1 root root 1.7K Dec 12 20:09 pre-commit.sh
-rw-r--r-- 1 root root  139 Dec 12 20:09 setup.cfg
-rw-r--r-- 1 root root 5.2K Dec 12 20:09 tier1_tests.py
-rw-r--r-- 1 root root 1.3K Dec 12 20:09 utility.py

```

When I do:

```
root@0cc7691cbb6f:/b2_fuse# python b2fuse.py b2-mount
Traceback (most recent call last):
  File "b2fuse.py", line 28, in <module>
    import yaml
ImportError: No module named 'yaml'

root@0cc7691cbb6f:/b2_fuse# b2fuse.py -h
bash: b2fuse.py: command not found

root@0cc7691cbb6f:/b2_fuse# python b2fuse.py -h
Traceback (most recent call last):
  File "b2fuse.py", line 28, in <module>
    import yaml
ImportError: No module named 'yaml'
```

What is wrong ? Thank you in advance :)

**Comment by falense** [comment]
try "sudo apt-get install python-yaml"

2016-12-12 21:25 GMT+01:00 Pascal Andy <notifications@github.com>:

**Comment by pascalandy** [comment]
Nope same story. I even used a plain Ubuntu image this time.

```
FROM phusion/baseimage:0.9.18

RUN \
	sudo apt-get update -q && sudo apt-get -qy upgrade && \
	curl -O https://bootstrap.pypa.io/get-pip.py && \
	sudo apt-get install -qy --no-install-recommends \
		\
		nano \
		wget \
		git \
		\
		python-yaml \
		python-pip && \
		\
		pip install fusepy && \
		pip install b2 && \
		\
		git clone https://github.com/sondree/b2_fuse && \
		\
		echo "Let's clean up the shop" && \
		apt-get clean && \
		rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    	echo "apt-get install is finished"
	
WORKDIR /b2_fuse
```

**Comment by falense** [comment]
Well that is the library you need and your new build/image file looks good. 

Best

**Comment by pascalandy** [comment]
OK. Please leave this open. I'll mess around. Thank!

**Comment by falense** [comment]
How is this coming? Do you need further assistance?

**Comment by pascalandy** [comment]
You can close. Thanks!

**Comment by balupton** [comment]
@pascalandy did you figure this out, I'm trying to do the same

my use case is I want to setup https://hub.docker.com/r/linuxserver/plex/ + b2fuze on a http://balupton.com/vultr cloud instance, so I can have my media library in the cloud, and never have to worry about is my plex server running and the hdd attached

**Comment by pascalandy** [comment]
No I didn't but something alike is in my backlog. See 🌟 [MUST-05) Storage driver](http://firepress.org/blog/technical-challenges-we-are-facing-now/). 

Cheers!
