### ISSUE TITLE
Error parsing config file, related to python version (2.7 vs 3)?

### ISSUE THREAD

**Issue by omgbox** [sondree/b2_fuse#4]
python b2fuse.py /home/nodejs/bucket
Traceback (most recent call last):
  File "b2fuse.py", line 499, in <module>
    main(args.mountpoint, args.account_id, args.application_key, args.bucket_id)
  File "b2fuse.py", line 491, in main
    with B2Fuse(account_id, application_key, bucket_id) as filesystem:
  File "b2fuse.py", line 93, in **init**
    config = load_config()
  File "b2fuse.py", line 86, in load_config
    return yaml.load(f.read())
  File "/usr/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 143, in parse_implicit_document_start
    StreamEndToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<string>", line 1, column 23:
    accountId:SecretXXXXXXX 
                          ^

**Comment by falense** [comment]
I am afraid your going to have to be a bit more detailed on the problem your facing. It does however seem that it has problems parsing you config file. 

This is the correct format:

> accountId: "youraccountid"
> applicationKey: "yourapplicationid"
> bucketId: "yourbucketid"

Note that there is a space between ":" and each value.

**Comment by falense** [comment]
From you error message it appears you are using python2.7. This should work fine.

**Comment by omgbox** [comment]
its working, fused into folder  , space seemed like the problem

**Comment by falense** [comment]
Excellent, I'll consider this issue resolved. Please open another issue if you have additional problems ;)
