### ISSUE TITLE
When attempting to mount error occurs

### ISSUE THREAD

**Issue by jeremybrown82** [sondree/b2_fuse#62]
Running clean install of ubuntu 14.04 and followed instructions exactly.

jeremybrown82@s125553:/etc/b2fuse$ python /etc/b2fuse/b2fuse.py /mnt/b2fuse-mount
Traceback (most recent call last):
  File "/etc/b2fuse/b2fuse.py", line 32, in <module>
    from b2fuse_main import B2Fuse
  File "/etc/b2fuse/b2fuse_main.py", line 37, in <module>
    from b2.api import B2Api
  File "/usr/local/lib/python2.7/dist-packages/b2/api.py", line 15, in <module>
    from .b2http import B2Http
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 13, in <module>
    import arrow
  File "/usr/local/lib/python2.7/dist-packages/arrow/__init__.py", line 3, in <module>
    from .arrow import Arrow
  File "/usr/local/lib/python2.7/dist-packages/arrow/arrow.py", line 19, in <module>
    from arrow import util, locales, parser, formatter
  File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 12, in <module>
    from backports.functools_lru_cache import lru_cache  # pragma: no cover
ImportError: No module named backports.functools_lru_cache

**Comment by falense** [comment]
This is an issue with the underlying library B2 Command Line Tool. I suggest you report it there (https://github.com/Backblaze/B2_Command_Line_Tool). Based on the log output I think it has to do with you running 14.04 which is unsupported.

**Comment by falense** [comment]
Closed as inactive
