### ISSUE TITLE
cannot mount bucket

### ISSUE THREAD

**Issue by nm3xyz** [sondree/b2_fuse#66]
Hello, just registered to BackBlaze, create an app-key and a bucket named marioborg. Tried to mount it but fails with the following message:

mario@mario3 ~/dl % b2fuse --config_filename ~/local/etc/b2fuse.yaml ~/mnt/tmp
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 693, in readdir
    fip.contents.fh):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/usr/local/lib/python2.7/dist-packages/b2fuse/b2fuse_main.py", line 236, in readdir
    self._update_directory_structure()
  File "/usr/local/lib/python2.7/dist-packages/b2fuse/b2fuse_main.py", line 131, in _update_directory_structure
    online_files = [l[0].as_dict() for l in self.bucket_api.ls()]#self.bucket_api.list_file_names()['files']
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2fuse/cached_bucket.py", line 86, in ls
    result = [f for f in super(CachedBucket, self).ls()]
  File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 230, in ls
    response = session.list_file_names(self.id_, start_file_name, fetch_count)
  File "/usr/local/lib/python2.7/dist-packages/b2/session.py", line 38, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 351, in list_file_names
    maxFileCount=max_file_count
  File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 139, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 299, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 272, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 116, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 52, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
BadJson: Bad request: Invalid bucketId: marioborg

**Comment by falense** [comment]
BucketID is the alphanumeric string, you have entered the bucket name.

**Comment by nm3xyz** [comment]
Lol, of course! Thanks...
