### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by afxgroup** [sondree/b2_fuse#71]
Another error that is getting out:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 530, in unlink
    return self.operations('unlink', path.decode(self.encoding))
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/opt/b2_fuse/b2fuse/b2fuse_main.py", line 363, in unlink
    self._remove_local_file(path)
  File "/opt/b2_fuse/b2fuse/b2fuse_main.py", line 136, in _remove_local_file
    self.open_files[path].delete(delete_online)
  File "/opt/b2_fuse/b2fuse/filetypes/B2SequentialFileMemory.py", line 91, in delete
    self.file_info['fileId'], self.file_info['fileName']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by falense** [comment]
It is impossible to debug this issue without additional information. What a your command line parameters. Config etc.

**Comment by afxgroup** [comment]
just a simply

b2fuse /mnt/b2 &

and in the config there are only the user parameters. Nothing else

**Comment by afxgroup** [comment]
I suppose this happens when proxmox in the backup script try to delete a file from that dir (reading the stacktrace..)

And indeed i have an error on backup

```
INFO: creating archive '/mnt/b2/dump/vzdump-lxc-101-2018_05_29-23_58_02.tar.gz'
INFO: Total bytes written: 1485230080 (1.4GiB, 5.2MiB/s)
INFO: gzip: write error: Bad address
```

If i remove all files and start the backup from scratch only the first VM is backupped. On the second one i get always this error

**Comment by falense** [comment]
Unfortunately I am unable to replicate this error. If you can provide me a step by step to replicate I will investigate.
