### ISSUE TITLE
`pip install b2fuse` fails on ubuntu focal 20.04

### ISSUE THREAD

**Issue by sneak** [sondree/b2_fuse#76]
```
root@remotefs:~# sudo pip install b2fuse

Collecting b2fuse
  Downloading https://files.pythonhosted.org/packages/67/e6/6884773918f9d05cd7a73d9c89e55caf0bf37b82022d144f6da407d75da1/b2fuse-1.3.tar.gz
Collecting PyYAML==3.12 (from b2fuse)
  Downloading https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 3.1MB/s
Collecting b2==1.1.0 (from b2fuse)
  Downloading https://files.pythonhosted.org/packages/21/3f/2ca1d3d3990b044549c26c0a0c5797bb1231709f8ce808caad1e8b4fcb70/b2-1.1.0.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 13.2MB/s
Collecting fusepy==2.0.4 (from b2fuse)
  Downloading https://files.pythonhosted.org/packages/70/aa/959d781b7ac979af1a9fbea0faffe06677c390907b56b8ce024eb9320451/fusepy-2.0.4.tar.gz
Collecting arrow>=0.8.0 (from b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/92/fa/f84896dede5decf284e6922134bf03fd26c90870bbf8015f4e8ee2a07bcc/arrow-0.15.5-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 14.3MB/s
Collecting futures>=3.0.5 (from b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/d8/a6/f46ae3f1da0cd4361c344888f59ec2f5785e69c872e175a748ef6071cdb5/futures-3.3.0-py2-none-any.whl
Collecting logfury>=0.1.2 (from b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/55/71/c70df1ef41721b554c91982ebde423a5cf594261aa5132e39ade9196fa3b/logfury-0.1.2-py2.py3-none-any.whl
Collecting requests>=2.9.1 (from b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 13.3MB/s
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/dist-packages (from b2==1.1.0->b2fuse) (1.14.0)
Collecting tqdm>=4.5.0 (from b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/47/55/fd9170ba08a1a64a18a7f8a18f088037316f2a41be04d2fe6ece5a653e8f/tqdm-4.43.0-py2.py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 13.9MB/s
Collecting backports.functools-lru-cache>=1.2.1; python_version == "2.7" (from arrow>=0.8.0->b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/da/d1/080d2bb13773803648281a49e3918f65b31b7beebf009887a529357fd44a/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
Collecting python-dateutil (from arrow>=0.8.0->b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 3.3MB/s
Collecting funcsigs (from logfury>=0.1.2->b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.9.1->b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 8.2MB/s
Collecting certifi>=2017.4.17 (from requests>=2.9.1->b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 5.2MB/s
Collecting chardet<4,>=3.0.2 (from requests>=2.9.1->b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 11.4MB/s
Collecting idna<3,>=2.5 (from requests>=2.9.1->b2==1.1.0->b2fuse)
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 13.9MB/s
Building wheels for collected packages: b2fuse, PyYAML, b2, fusepy
  Running setup.py bdist_wheel for b2fuse ... done
  Stored in directory: /root/.cache/pip/wheels/e5/23/c4/476d431f1de1f5cad7b9890f4eeb193d8e5d7cd4402aa5654c
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/03/05/65/bdc14f2c6e09e82ae3e0f13d021e1b6b2481437ea2f207df3f
  Running setup.py bdist_wheel for b2 ... done
  Stored in directory: /root/.cache/pip/wheels/c7/21/b7/6a3e8c2d9f0aab3154b2c39c883d7c759e33260726a0682108
  Running setup.py bdist_wheel for fusepy ... done
  Stored in directory: /root/.cache/pip/wheels/c5/fc/87/bd3c9942ab2366b4838ea6588f98fd096facb0dbf123e57399
Successfully built b2fuse PyYAML b2 fusepy
Installing collected packages: PyYAML, backports.functools-lru-cache, python-dateutil, arrow, futures, funcsigs, logfury, urllib3, certifi, chardet, idna, requests, tqdm, b2, fusepy, b2fuse
  Found existing installation: PyYAML 5.3
    Not uninstalling pyyaml at /usr/lib/python2.7/dist-packages, outside environment /usr
    Can't uninstall 'PyYAML'. No files were found to uninstall.
Successfully installed PyYAML-3.12 arrow-0.15.5 b2-1.1.0 b2fuse-1.3 backports.functools-lru-cache-1.6.1 certifi-2019.11.28 chardet-3.0.4 funcsigs-1.0.2 fusepy-2.0.4 futures-3.3.0 idna-2.9 logfury-0.1.2 python-dateutil-2.8.1 requests-2.23.0 tqdm-4.43.0 urllib3-1.25.8
root@remotefs:~#
root@remotefs:~# b2fuse
Traceback (most recent call last):
  File "/usr/local/bin/b2fuse", line 6, in <module>
    from b2fuse.b2fuse import main
  File "/usr/local/lib/python2.7/dist-packages/b2fuse/b2fuse.py", line 32, in <module>
    from b2fuse_main import B2Fuse
  File "/usr/local/lib/python2.7/dist-packages/b2fuse/b2fuse_main.py", line 37, in <module>
    from b2.api import B2Api
  File "/usr/local/lib/python2.7/dist-packages/b2/api.py", line 15, in <module>
    from .b2http import B2Http
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 13, in <module>
    import arrow
  File "/usr/local/lib/python2.7/dist-packages/arrow/__init__.py", line 3, in <module>
    from .api import get, now, utcnow
  File "/usr/local/lib/python2.7/dist-packages/arrow/api.py", line 10, in <module>
    from arrow.factory import ArrowFactory
  File "/usr/local/lib/python2.7/dist-packages/arrow/factory.py", line 18, in <module>
    from arrow import parser
  File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 15, in <module>
    from backports.functools_lru_cache import lru_cache  # pragma: no cover
ImportError: No module named functools_lru_cache
root@remotefs:~#
```

**Comment by sneak** [comment]
Seems to work when I install from git.

**Comment by falense** [comment]
This is actually an error in B2CommandLineTool which this project depends on. If it persists it should be reported here https://github.com/Backblaze/B2_Command_Line_Tool

**Comment by falense** [comment]
Working on a new updated version with some fixes as B2CommandLineTool has changed. Try this out if you are still interested: https://github.com/sondree/b2_fuse/tree/version1.4

**Comment by falense** [comment]
I will update the PIP package version too once this 1.4 gets off the ground, in the meanwhile I consider this closed. Thanks for your interest in the project!
