### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by YaPaY** [sondree/b2_fuse#77]
Hello,

For Raspberry I installed phyton2 version but if enter the command I am getting error

pi@raspberrypi:~ $ b2fuse
Traceback (most recent call last):
  File "/usr/local/bin/b2fuse", line 6, in <module>
    from b2fuse.b2fuse import main
  File "/usr/local/lib/python2.7/dist-packages/b2fuse/b2fuse.py", line 32, in <module>
    from b2fuse_main import B2Fuse
  File "/usr/local/lib/python2.7/dist-packages/b2fuse/b2fuse_main.py", line 37, in <module>
    from b2.api import B2Api
  File "/usr/local/lib/python2.7/dist-packages/b2/api.py", line 15, in <module>
    from .b2http import B2Http
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 13, in <module>
    import arrow
  File "/usr/local/lib/python2.7/dist-packages/arrow/__init__.py", line 3, in <module>
    from .api import get, now, utcnow
  File "/usr/local/lib/python2.7/dist-packages/arrow/api.py", line 10, in <module>
    from arrow.factory import ArrowFactory
  File "/usr/local/lib/python2.7/dist-packages/arrow/factory.py", line 18, in <module>
    from arrow import parser
  File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 15, in <module>
    from backports.functools_lru_cache import lru_cache  # pragma: no cover
ImportError: No module named functools_lru_cache

**Comment by falense** [comment]
This is an error in B2 Command Line tool, likely due to missing default
library on RPi. Report the issue here
https://github.com/Backblaze/B2_Command_Line_Tool

**Comment by YaPaY** [comment]
ok thanks I fixed b2 command tool problem but now I am getting this error

pi@raspberrypi:~ $ b2fuse
Traceback (most recent call last):
  File "/usr/local/bin/b2fuse", line 6, in <module>
    from b2fuse.b2fuse import main
  File "/usr/local/lib/python3.7/dist-packages/b2fuse/b2fuse.py", line 32, in <module>
    from b2fuse_main import B2Fuse
ModuleNotFoundError: No module named 'b2fuse_main'

**Comment by YaPaY** [comment]
pi@raspberrypi:~/b2_fuse-master $ b2fuse
Traceback (most recent call last):
  File "/usr/local/bin/b2fuse", line 11, in <module>
    load_entry_point('b2fuse==1.3', 'console_scripts', 'b2fuse')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/b2fuse/b2fuse.py", line 32, in <module>
    from b2fuse_main import B2Fuse
ModuleNotFoundError: No module named 'b2fuse_main'


what is the reason

**Comment by YaPaY** [comment]
end of config I am getting below error
What mount point do you want for the "turkfilm" bucket?
/media/b2       
Optional parameters: --enable_hashfiles --use_disk --temp_folder
Add any optional parameter? (y/n)
n
No optional parameters will be added.

additional parameters that will be added:   ""


To unmount this bucket use this command as a normal user:
        fusermount -u "/media/b2"

pi@raspberrypi:~/b2_fuse-master $ Traceback (most recent call last):
  File "/home/pi/b2_fuse-master/b2fuse/b2fuse.py", line 32, in <module>
    from .b2fuse_main import B2Fuse
ModuleNotFoundError: No module named '__main__.b2fuse_main'; '__main__' is not a package
