### ISSUE TITLE
expired_auth_token error after running it for couple days

### ISSUE THREAD

**Issue by bedros** [sondree/b2_fuse#8]
I mounted for couple days then tried to copy a file to it, and got the following error

I used python 2.7.11 and

command

 "b2fuse.py /mnt/mountpoint"

`2016-05-12 23:37:53,498:INFO:_list_dir 
Error returned from server:

URL: https://api001.backblaze.com/b2api/v1/b2_list_file_names
Params: {"bucketId": "4f709ffffb2796275f4d0219", "startFileName": "", "maxFileCount": 1000}
Headers: {'Authorization': u'3_20160510072929_5c2daf8dd724a7e42cd1009b_b88d1324234243813534dfa81df3aaab10a0b74d3a9d99a24_001_acct'}

{
  "code": "expired_auth_token",
  "message": "Authorization token has expired",
  "status": 401
}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 511, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 759, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "b2fuse.py", line 174, in getattr
    elif self._exists(path):
  File "b2fuse.py", line 131, in _exists
    if path in self.bucket.list_dir():
  File "/mnt/redline/Projects/python/b2_fuse/b2_fuse/b2bucket_cached.py", line 118, in list_dir
    return  map(lambda x: x['fileName'], self._list_dir(startFilename))
  File "/mnt/redline/Projects/python/b2_fuse/b2_fuse/b2bucket_cached.py", line 114, in _list_dir
    result = super(B2BucketCached, self)._list_dir(startFilename)
  File "/mnt/redline/Projects/python/b2_fuse/b2_fuse/b2bucket.py", line 84, in _list_dir
    resp = call_api(self.api_url, api_call, self.account_token, call_params)
  File "/mnt/redline/Projects/python/b2_fuse/b2_fuse/b2_python_pusher.py", line 85, in call_api
    with OpenUrl(url, request_data, headers) as f:
  File "/mnt/redline/Projects/python/b2_fuse/b2_fuse/b2_python_pusher.py", line 71, in __enter__
    sys.exit(1)
SystemExit: 1
`

**Comment by falense** [comment]
There is currently no handling of timeouts and only basic error handling implemented. A quick fix is obviously to remount the bucket. 

I have been planning to have another go at error handling soon, as the B2 API has gotten a lot more mature recently.

**Comment by falense** [comment]
Finished porting to new backend for interfacing with B2, this should help with this issue as well. I'll leave it open in case this is still a problem though. Let me know if you try it out. 

Best
